version: '3.8'

services:
  harpia_ingestion_ex:
    build: 
      dockerfile: ./docker/ingestion.dockerfile
      context: .
    container_name: harpia_ingestion_ex
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    networks:
      - harpia_elx
    volumes:
      - ./src:/app
      - /app/deps/ # this excludes the /app/deps/ folder from the volume
      - /app/_build/ # this excludes the /app/_build/ folder from the volume
    depends_on:
      - zookeeper
      - kafka
  
  # kafka services
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - harpia_elx
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeperdata:/bitnami/zookeeper
  
  kafka:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    expose:
      - "9092"
      - "9093"
    networks:
      - harpia_elx
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="kafka_capstone_event_bus:1:1"
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafkadata:/bitnami/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    networks:
      - harpia_elx
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

networks:
  harpia_elx:
    driver: bridge

volumes:
  zookeeperdata:
    driver: local
  kafkadata:
    driver: local
